// Re-export tipos derivados do Prisma para consumo nos apps.
export type {
  Loja,
  Funcionario,
  User,
  UsuarioLoja,
  Permissao,
  PapelUsuario,
  Grupo,
  Subgrupo,
  Produto,
  ProdutoMeta,
  ListaContagem,
  ProdutoLista,
  Contagem,
  Lancamento,
  Etiqueta,
  StatusContagem,
  SyncRun,
  SyncStatus,
  Recebimento,
  RecebimentoItem,
  StatusRecebimento,
  ProdutoFornecedorMap,
  NotaFiscalImportada,
  NfStatus,
  SefazSync,
  SefazSyncStatus,
} from '@prisma/client';
